config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  resources :routes
  resources :wagons
  resources :tickets
  get 'welcome/index'

  root 'welcome#index'

end

app/models/train.rb
class Train < ActiveRecord::Base
  validates :number, presence: true

  belongs_to :railway_station
  belongs_to :route
  has_many :tickets
  has_many :wagons
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :route_id, :railway_station_id, :wagons_id)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
  def count_top_places(wagons)
    sum = 0
    wagons.each do |wagon|
      sum = wagon.count_top_places + sum
    end
    sum
  end

  def count_bottom_places(wagons)
    sum = 0
    wagons.each do |wagon|
      sum = wagon.count_bottom_places + sum
    end
    sum
  end
end

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
<%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :railway_station_id, "Поточна станція" %>
    <%= f.collection_select :railway_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= f.label :route_id, "Поточний маршрут" %>
    <%= f.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :wagons_id, "Вагони:" %>
    <%= f.collection_select :wagons_id, Wagon.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Show', train %></td>
  <td><%= link_to 'Edit', edit_train_path(train) %></td>
  <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form' %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form' %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер:</strong>
  <%= @train.number %>
</p>
<p>
  <strong> На Станції:</strong>
  <% if @train.railway_station.present? %>
    <%= @train.railway_station.title %>
  <% else %>
    Не вказано
  <% end %>
</p>

<p>
  <strong> На маршуті:</strong>
  <% if @train.route.present? %>
    <%= @train.route.name %>
  <% else %>
    Не вказано
  <% end %>
</p>

<p>
  <br>
  <strong>Загальна кількість вагонів:</strong>
  <%= @train.wagons.count() %>
  <br>
  <strong>Загальна кількість купейних вагонів:</strong>
  <%= @train.wagons.cargo.count() %>
  <%= count_top_places(@train.wagons.cargo) %>
  <%= count_bottom_places(@train.wagons.cargo) %>
  <br>
  <strong>Загальна кількість плацкартних вагонів:</strong>
  <%= @train.wagons.seat_card.count() %>
  <%= count_top_places(@train.wagons.seat_card) %>
  <%= count_bottom_places(@train.wagons.seat_card) %>
</p>

<p>
  <strong> Вагони:</strong>
  <% if @train.wagons.present? %>

    <% @train.wagons.each do |wagon| %>
    <br>
      <%= wagon.wagon_type %>
      <%= wagon.count_top_places %>
      <%= wagon.count_bottom_places %>
    <% end %>
  <% else %>
    Не вказано
  <% end %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %>
<%= link_to 'Back', trains_path %>