config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  resources :routes
  resources :wagons
  resources :tickets
  get 'welcome/index'

  root 'welcome#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :train
  belongs_to :first_station, class_name: "RailwayStation", foreign_key: "first_station_id"
  belongs_to :last_station, class_name: "RailwayStation", foreign_key: "last_station_id"
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show

  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket
    else
      render :new
    end
  end

  def edit

  end

  def update

    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:train_id, :first_station_id, :last_station_id, :first_name, :last_name)
  end
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
<%= render 'common/errors', resource: @ticket %>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_station %><br>
    <%= f.collection_select :first_station_id, RailwayStation.all, :id, :title %>
  </div>
  <div class="field">
    <%= f.label :last_station %><br>
    <%= f.collection_select :last_station_id, RailwayStation.all, :id, :title %>
  </div>
  <div class="field">
    <%= f.label :train %><br>
    <%= f.collection_select :train_id, Train.all, :id, :number%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.train %></td>
      <td><%= link_to 'Show', ticket %></td>
      <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
      <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full Name:</strong>
  <%= @ticket.first_name %>
  <%= @ticket.last_name %>
</p>
<p>
  <strong>First Station:</strong>
  <%= @ticket.first_station.title %>
</p>
<p>
  <strong>Last Station:</strong>
  <%= @ticket.last_station.title %>
</p>
<p>
  <strong>Train:</strong>
  <%= link_to @ticket.train.number, train_path(@ticket.train) %>
</p>


<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>