config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  resources :routes
  resources :wagons
  resources :tickets
  get 'welcome/index'

  root 'welcome#index'

end

app/models/railway_station.rb
class RailwayStation < ActiveRecord::Base
  validates :title, presence: true

  has_many :trains
  has_and_belongs_to_many :routes
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  # GET /railway_stations
  # GET /railway_stations.json
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1
  # GET /railway_stations/1.json
  def show
  end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit
  end

  # POST /railway_stations
  # POST /railway_stations.json
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully created.' }
        format.json { render :show, status: :created, location: @railway_station }
      else
        format.html { render :new }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railway_stations/1
  # PATCH/PUT /railway_stations/1.json
  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully updated.' }
        format.json { render :show, status: :ok, location: @railway_station }
      else
        format.html { render :edit }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railway_stations/1
  # DELETE /railway_stations/1.json
  def destroy
    @railway_station.destroy
    respond_to do |format|
      format.html { redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/railway_stations/_form.html.erb
<%= form_for(@railway_station) do |f| %>
<%= render 'common/errors', resource: @railway_station %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to 'Show', railway_station %></td>
  <td><%= link_to 'Edit', edit_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Destroy', railway_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form' %>

<%= link_to 'Show', @railway_station %> |
<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to 'New Railway station', new_railway_station_path %>

app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form' %>

<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<% if @railway_station.routes.empty? %>
  <p>Станція не належить до жодного маршруту</p>
  <% else %>
  <p>Станція належить наступним маршрутам:</p>
    <ul>
  <% @railway_station.routes.each do |route| %>
      <li><%= route.name %></li>
  <% end %>
   </ul>
<% end %>

<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>