config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  resources :routes
  resources :wagons
  resources :tickets
  get 'welcome/index'

  root 'welcome#index'

end

app/models/wagon.rb
class Wagon < ActiveRecord::Base
  belongs_to :train

  validates :number, :top_seats, :bottom_seats, presence: true
end

app/controllers/wagons_controller.rb
class WagonsController < ApplicationController
  before_action :set_wagon, only: [:show, :edit, :update, :destroy]

  def index
    @wagons = Wagon.all
  end

  def show
    @wagon
  end

  def new
    @wagon = Wagon.new
  end

  def edit
  end

  def create
    @wagon = Wagon.new(wagon_params)

    respond_to do |format|
      if @wagon.save
        format.html { redirect_to @wagon, notice: 'Train was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @wagon.update(wagon_params)
        format.html { redirect_to @wagon, notice: 'Train was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @wagon.destroy
    respond_to do |format|
      format.html { redirect_to wagons_url, notice: 'Wagon was successfully destroyed.' }
    end
  end

  private

  def set_wagon
    @wagon = Wagon.find(params[:id])
  end

  def wagon_params
    params.require(:wagon).permit(:number, :train_id, :wagon_type, :count_top_places, :count_bottom_places)
  end
end

app/views/wagons/_form.html.erb
<%= form_for(@wagon) do |f| %>
  <%= render 'common/errors', resource: @wagon %>

  <div class="field">
    <%= f.label :top_seats %><br>
    <%= f.number_field :top_seats %>
  </div>

  <div class="field">
    <%= f.label :bottom_seats %><br>
    <%= f.number_field :count_bottom_places %>
  </div>

  <div class="select">

      <%= f.label :wagon_type %>
      <%= f.select :wagon_type,  options_for_select(Wagon.wagon_types.map {|key, value| [key.titleize, Wagon.wagon_types.key(value)]}, @wagon.wagon_type) %>

  </div>

  <div class="field">
    <%= f.label :train_id, "Поточний поїзд" %>
    <%= f.collection_select :train_id, Train.all, :id, :number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wagons/_wagon.html.erb
<tr>
  <td><%= wagon.type %></td>
  <td><%= wagon.top_seats %></td>
  <td><%= wagon.bottom_seats %></td>
  <td><%= wagon.side_top_seats %></td>
  <td><%= wagon.side_bottom_seats %></td>
  <td><%= link_to 'Show', wagon %></td>
  <td><%= link_to 'Edit', edit_wagon_path(wagon) %></td>
  <td><%= link_to 'Destroy', wagon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/wagons/edit.html.erb
<h1>Editing Wagon</h1>

<%= render 'form' %>

<%= link_to 'Show', @wagon %> |
<%= link_to 'Back', wagons_path %>

app/views/wagons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wagons</h1>

<table>
  <thead>
  <tr>
    <th>Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @wagons %>
  </tbody>
</table>

<br>

<%= link_to 'New Wagon', new_wagon_path %>

app/views/wagons/new.html.erb
<h1>New Wagon</h1>

<%= render 'form' %>

<%= link_to 'Back', wagons_path %>

app/views/wagons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер:</strong>
  <%= @wagon.count_top_places %>
  <%= @wagon.count_bottom_places %>
</p>
<p>
  <strong> Належить поїзду:</strong>
  <% if @wagon.train.present? %>
    <%= @wagon.train.number %>
  <% else %>
    Не вказано
  <% end %>
</p>


<%= link_to 'Edit', edit_wagon_path(@wagon) %> |
<%= link_to 'Back', wagons_path %>